// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClBAs-WWG4FMGo5ZsEsNh2dvnpVSCuEJ4',
    appId: '1:733287524302:web:3d4256e1e77b658b616d9f',
    messagingSenderId: '733287524302',
    projectId: 'tutor-finder-dotio',
    authDomain: 'tutor-finder-dotio.firebaseapp.com',
    storageBucket: 'tutor-finder-dotio.firebasestorage.app',
    measurementId: 'G-J6SNR5TTR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYIRxOfoMhIGTbNKXISehs1IutCRWJj8Q',
    appId: '1:733287524302:android:ec527273f0120e4c616d9f',
    messagingSenderId: '733287524302',
    projectId: 'tutor-finder-dotio',
    storageBucket: 'tutor-finder-dotio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLnXaf6LP9YwJOWdMJoSwfK0T13oFI9_Y',
    appId: '1:733287524302:ios:0d46169fc6eb0d5e616d9f',
    messagingSenderId: '733287524302',
    projectId: 'tutor-finder-dotio',
    storageBucket: 'tutor-finder-dotio.firebasestorage.app',
    iosClientId: '733287524302-4gltst40apeie00h5uu5aaq8nbhk5vip.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorFinderApp',
  );
}
